Repository open-edge-platform/scenescape, pull requests merged in 2025-08, with the labels that each got.

#242 [ITEP-68209] Add images description + change publishing repo
  .github/workflows/weekly-build.yml
  autocalibration/Dockerfile
  controller/Dockerfile
  manager/Dockerfile
Labels: github_actions, docker, run-bat

#230 ITEP-72978: Enable smart parking DLSP with SceneScape
  controller/src/controller/scene.py
  controller/src/schema/metadata.schema.json
  dlstreamer-pipeline-server/user_scripts/DeepScenario.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_3d_detector.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_adapter.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_policies.py
  docs/user-guide/How-to-run-LPR-with-3D-object-detection.md
  docs/user-guide/images/3D-object.gif
Labels: run-bat

#247 ITEP-73273: Fix unit tests
  manager/src/django/views.py
  tests/Makefile
  tests/Makefile.sscape
  tests/sscape_tests/account-security/pytest.ini
  tests/sscape_tests/cam/pytest.ini
  tests/sscape_tests/singleton_sensor/pytest.ini
  tests/sscape_tests/views/conftest.py
Labels: run-bat

#239 [ITEP-73356] Running DLS and k8s tests in pipeline
  .github/workflows/tests-bat.yml
  Makefile
  tests/Makefile
Labels: github_actions, run-bat

#261 ITEP-68814: Fix markerless camera calibration
  autocalibration/requirements-runtime.txt
  autocalibration/src/markerless_camera_calibration_controller.py
  autocalibration/src/polycam_to_images.py
  autocalibration/src/reloc/requirements.txt
  controller/src/controller/scene.py
Labels: run-bat

#263 Fixed how coverity builds are named and zipped before pushing to analysis server
  .github/workflows/coverity.yml
Labels: run-bat

#265 ITEP-72774 - Add Apache timeout to prevent long delays when WebSocket backend doesn't listen on port
  manager/config/default-ssl.conf
Labels: run-bat

#266 NEX-T10448 Re-enable indent cheking in tests
  .github/workflows/lint.yml
  Makefile
  dlstreamer-pipeline-server/user_scripts/DeepScenario.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_3d_detector.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_adapter.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_policies.py
  manager/src/django/models.py
  manager/src/django/views.py
  manager/tools/replace_sscape.py
  percebro/src/open_pose.py
  scene_common/src/mesh_util.py
  tests/Makefile
  tests/functional/tc_dlstreamer_api.py
  tests/scripts/build-time.py
  tests/scripts/checkIndent
  tests/scripts/check_common.py
  tests/scripts/reindent
  tests/sscape_tests/mesh_util/test_mesh_util.py
  tests/sscape_tests/scene_pytest/test_scene.py
  tests/ui/common_ui_test_utils.py
  tests/ui/tc_out_of_box.py
Labels: run-bat

#260 Dependabot updates
  .github/resources/coverity-requirements.txt
  .github/resources/requirements.txt
  .github/workflows/auto-update.yml
  .github/workflows/checks-and-scans.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/post-merge.yml
  .github/workflows/pre-merge.yml
  .github/workflows/publish-docs.yml
  .github/workflows/weekly-build.yml
  kubernetes/init-images/Dockerfile-models
Labels: dependencies, github_actions, docker, python, run-bat

#246 ITEP-73434: depth filter for 3D objects in DLSPS
  controller/src/controller/scene.py
  dlstreamer-pipeline-server/user_scripts/DeepScenario.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_adapter.py
  docs/user-guide/How-to-run-LPR-with-3D-object-detection.md
Labels: run-bat

#267 ITEP-73546: Auto camera calibration works with DLSPS
  autocalibration/src/atag_camera_calibration_controller.py
  autocalibration/src/auto_camera_calibration_context.py
  autocalibration/src/auto_camera_calibration_controller.py
  autocalibration/src/auto_camera_calibration_model.py
  autocalibration/src/markerless_camera_calibration.py
  autocalibration/src/markerless_camera_calibration_controller.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_adapter.py
  sample_data/docker-compose-dl-streamer-example.yml
  tests/Makefile
  tests/compose/camcalibration.yml
  tests/runtest
Labels: run-bat, v1.4.0-rc2

#282 Fix orphaned-sensor test
  manager/src/django/serializers.py
  tests/Makefile
  tests/Makefile.functional
Labels: run-bat, v1.4.0

#287 Run demo before DBS scan
  .github/workflows/docker-bench-security.yaml
Labels: github_actions, run-bat

#245 ITEP-72972: autogenerate UI password in K8S deployment
  deploy.sh
  kubernetes/Makefile
  kubernetes/README.md
  kubernetes/scenescape-chart/templates/pgserver-dep.yaml
  kubernetes/scenescape-chart/values.yaml
Labels: run-bat, v1.4.0

#289 ITEP-74030: Update RESTler script
  manager/src/django/serializers.py
  tests/security/fuzzing/Dockerfile
  tests/security/fuzzing/README.md
  tests/security/fuzzing/run_fuzzing.sh
Labels: run-bat

#300 ITEP-71913 Fix most image & filesystem scan Trivy issues
  controller/src/robot_vision/Dockerfile
  model_installer/Dockerfile
  model_installer/Makefile
  sources.Dockerfile
Labels: run-bat, v1.4.0

#305 ITEP-74093: Improvements to content flow in Getting Started Guide
  docs/user-guide/Getting-Started-Guide.md
Labels: run-bat

#310 [CI] Improve Trivy scanning
  .github/resources/sdl/trivy_config.yml
  .github/workflows/trivy.yml
Labels: run-bat

#311 Orch-ci actions update
  .github/workflows/auto-update.yml
  .github/workflows/bandit.yml
  .github/workflows/clamav.yml
  .github/workflows/docs-post-merge.yml
  .github/workflows/docs-pre-merge.yml
  .github/workflows/gitleaks.yml
  .github/workflows/lint.yml
  .github/workflows/publish-docs.yml
  .github/workflows/weekly-build.yml
Labels: run-bat

#313 ITEP-73725: change in object library reflect without refreshing the 3D UI web page
  manager/src/static/js/assetmanager.js
  manager/src/static/js/scenescape3d.js
Labels: run-bat

#291 ITEP-24349: new polycam zip structure
  autocalibration/src/markerless_camera_calibration_controller.py
  manager/src/django/forms.py
  manager/src/django/models.py
  manager/src/django/validators.py
Labels: run-bat

#318 Fix: Update LWS version to `4.3.3` in `broker/Dockerfile`
  broker/Dockerfile
Labels: run-bat

#235 ITEP-73107: Controller deployment hardening
  Makefile
  common.mk
  controller/Dockerfile
  controller/src/controller-init
  controller/src/robot_vision/Dockerfile
  kubernetes/scenescape-chart/templates/scene-dep.yaml
  sample_data/docker-compose-dl-streamer-example.yml
  sample_data/docker-compose-dls-perf.yml
  sample_data/docker-compose-example.yml
  tests/compose/ovms.yml
  tests/compose/pgserver.yml
  tests/compose/pgserver_default.yml
  tests/compose/scene.yml
  tests/compose/scene_no_ntp.yml
  tests/compose/scene_reid.yml
  tools/scenescape-start
Labels: run-bat

#317 Update `dlstreamer-pipeline-server` version tag to `3.1.0`
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_3d_detector.py
  docs/user-guide/How-to-run-LPR-with-3D-object-detection.md
  kubernetes/scenescape-chart/values.yaml
  sample_data/docker-compose-dl-streamer-example.yml
  sample_data/docker-compose-dls-perf.yml
  tests/compose/dlstreamer/queuing_video.yml
  tests/compose/dlstreamer/queuing_video_no_ntp.yml
  tests/compose/dlstreamer/queuing_video_reid.yml
  tests/compose/dlstreamer/retail_video.yml
  tests/compose/dlstreamer/retail_video_no_ntp.yml
  tests/compose/dlstreamer/retail_video_reid.yml
  tests/perf_tests/compose/docker-compose-inference_performance.yml
Labels: run-bat

#319 ITEP-74690 Run main processes in production containers as non root
  autocalibration/Dockerfile
  autocalibration/src/camcalibration-init
  controller/Dockerfile
  controller/src/controller-init
  manager/Makefile
  manager/config/webserver-init
  tools/authsecrets/Makefile
  tools/certificates/Makefile
Labels: run-bat

#296 ITEP-74692: Fix volumes for DLStreamer pipeline server on tests compose files
  tests/compose/dlstreamer/broker.yml
  tests/compose/dlstreamer/queuing_video.yml
  tests/compose/dlstreamer/queuing_video_no_ntp.yml
  tests/compose/dlstreamer/queuing_video_reid.yml
  tests/compose/dlstreamer/retail_video.yml
  tests/compose/dlstreamer/retail_video_no_ntp.yml
  tests/compose/dlstreamer/retail_video_reid.yml
Labels: run-bat

#330 Revert ITEP-74692: Fix volumes for DLStreamer pipeline server on tests compose files #296
  tests/compose/dlstreamer/broker.yml
  tests/compose/dlstreamer/queuing_video.yml
  tests/compose/dlstreamer/queuing_video_no_ntp.yml
  tests/compose/dlstreamer/queuing_video_reid.yml
  tests/compose/dlstreamer/retail_video.yml
  tests/compose/dlstreamer/retail_video_no_ntp.yml
  tests/compose/dlstreamer/retail_video_reid.yml
Labels: run-bat

#326 Renamed workflows names
  .github/workflows/docs-build.yml
  .github/workflows/docs-publish.yml
Labels: github_actions, run-bat

#325 [ITEP-74149] Update Dockerfiles docs links
  controller/Dockerfile
  manager/Dockerfile
Labels: documentation, docker, run-bat

#334 [main] Update publish-documentation workflow
  .github/workflows/docs-publish.yml
Labels: github_actions, run-bat

#344 Fix Docker Bench Security warnings
  Makefile
  dlstreamer-pipeline-server/queuing-config.json
  dlstreamer-pipeline-server/retail-config.json
  sample_data/docker-compose-dl-streamer-example.yml
Labels: run-bat

#345 ITEP-74942: Update in image resolution reflects in viewport of camera calibration
  manager/src/static/js/cameracalibrate.js
  tests/ui/tc_camera_intrinsics.py
Labels: run-bat

#346 ITEP-74992: Return valid rotation from rotationToTarget
  scene_common/src/transform.py
Labels: run-bat

#347 ITEP-74941: Fix auto camera calibration intrinsics flow
  autocalibration/src/atag_camera_calibration_controller.py
  autocalibration/src/auto_camera_calibration_context.py
  autocalibration/src/markerless_camera_calibration_controller.py
  controller/src/controller/cache_manager.py
  dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_adapter.py
  manager/src/static/js/sscape.js
  manager/src/static/js/thing/scenecamera.js
Labels: run-bat

#348 Update `third-party-programs.txt` file
  third-party-programs.txt
Labels: run-bat

#340 ITEP-74810 Manager default Dockerfile healthcheck relies on `postgres`
  manager/Dockerfile
Labels: run-bat

#349 Update version to 1.4.0
  kubernetes/scenescape-chart/Chart.yaml
  version.txt
Labels: run-bat

#363 [CI/CD] Remove release branch from Dependabot update target
  .github/dependabot.yml
Labels: github_actions, run-bat

#362 Remove auto docs publish
  .github/workflows/docs-publish.yml
Labels: github_actions, run-bat

#377 Add scheduled cleanup and add volume cleaning
  .github/workflows/clean-runner.yml
  .github/workflows/tests-all.yml
  .github/workflows/tests-bat.yml
Labels: github_actions, run-bat
